import Head from "next/head";
import Link from "next/link";

const siteTitle = "T3 Notes App";

export default function Layout({
  children,
  home,
}: {
  children: React.ReactNode;
  home?: boolean;
}) {
  return (
    <div className="mx-auto flex min-h-screen flex-col px-2 2xl:container sm:px-4 lg:px-6">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="og:title" content={siteTitle} />
      </Head>
      <div className="navbar  px-0">
        <div className=" py-2 sm:py-4">
          <p className="text-3xl font-extrabold tracking-tight sm:text-4xl ">
            T3 <span className="text-accent">Note</span> App
          </p>
        </div>
      </div>

      <main className="flex grow flex-row">
        <div className="flex grow flex-col">{children}</div>
      </main>
      <footer className="">
        {!home && (
          <Link href="/">
            <p className="pb-8 pt-4 text-xl underline">← Back to home</p>
          </Link>
        )}
      </footer>
    </div>
  );
}
